Add support for sponsor nonce in the transactions
blockstack/stacks-blockchain-api pull request #1140
Opened 2022-04-07 17:02 UTC by asimm241

## Description
This PR fixes the problem with sponsor nonce in the API.  The possible next nonce could be incorrect because of the absence of sponsor_nonce for sponsored transactions.   This PR has added a field `sponsor_nonce` in the `txs` and the mempool table which will be set only in case of sponsored transactions just like the sponsored address. 

closes #1133 

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] API reference/documentation update
- [ ] Other

## Are documentation updates required?

## Testing information
_yet to add_

## Checklist
- [x] Code is commented where needed
- [ ] Unit test coverage for new or modified code paths
- [x] `npm run test` passes
- [ ] Changelog is updated
- [x] Tag 1 of @rafaelcr

2022-04-11 15:07 UTC, rafaelcr requested changes

2022-04-11 15:07 UTC, rafaelcr commented on src/datastore/postgres-store.ts
> +  sponsor_nonce: number;
This should be optional

2022-04-11 15:07 UTC, rafaelcr commented on src/datastore/postgres-store.ts
> +  sponsor_nonce: number;
Should be optional

2022-04-11 15:07 UTC, rafaelcr commented on src/datastore/postgres-store.ts
> +        WHERE sponsor_address = $1 AND sponsored= true
```suggestion
        WHERE sponsor_address = $1 AND sponsored = true
```

2022-04-12 12:46 UTC, zone117x commented on src/datastore/postgres-store.ts
> +          ) + 1;
I'm not really sure what the blockchain behavior is here. Does a sponsored transaction increment the nonce for two principals at once (as in, both the sender principal and sponsor principal nonces are both incremented)?

@kantai do you have a quick answer here?

2022-04-12 13:00 UTC, asimm241 commented on src/datastore/postgres-store.ts
> +          ) + 1;
Yes, when the transaction is sponsored both sender's nonce and sponsor_address's nonces are incremented. 

copied from [sip-005](https://github.com/stacksgov/sips/blob/main/sips/sip-005/sip-005-blocks-and-transactions.md) 
"This is a Lamport clock, used for ordering the transactions originating from **_and_** paying from an account."

2022-04-12 14:15 UTC, rafaelcr commented on src/datastore/postgres-store.ts
> +          ) + 1;
@asimm241 what I understand from that statement is that both parties will get their nonces increased in their respective addresses, however, in the current code you're affecting the nonce of one party with the max value from the nonce of the other party.

e.g. party A had nonce = 10 before the transaction, while party B (the sponsor) had nonce = 200
after the tx, party A nonce should be 11 and party B nonce should be 201, right?
In the current code, though, it seems party A's nonce will be reported as 201

2022-04-13 09:43 UTC, zone117x approved these changes
LGTM. Thanks for the research and explanations @asimm241!

2022-04-13 15:37 UTC, rafaelcr approved these changes
thanks @asimm241

2022-04-13 15:38 UTC, merged

2022-04-20 20:07 UTC, blockstack-devops commented
:tada: This PR is included in version 4.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@stacks/stacks-blockchain-api-types/v/4.0.0-beta.1)
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@stacks/blockchain-api-client/v/4.0.0-beta.1)
- [GitHub release](https://github.com/hirosystems/stacks-blockchain-api/releases/tag/v4.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-05-26 15:49 UTC, blockstack-devops commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@stacks/stacks-blockchain-api-types/v/4.0.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@stacks/blockchain-api-client/v/4.0.0)
- [GitHub release](https://github.com/hirosystems/stacks-blockchain-api/releases/tag/v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: