Harden api fix
blockstack/stacks-blockchain-api pull request #638
Opened 2021-07-06 15:54 UTC by asimm241

## Description
A hotfix for the API. 

For details refer to issue #636 

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] API reference/documentation update
- [ ] Other

## Does this introduce a breaking change?
NO

## Are documentation updates required?
NO

## Testing information

## Checklist
- [ ] Code is commented where needed
- [ ] Unit test coverage for new or modified code paths
- [ ] `npm run test` passes
- [ ] Changelog is updated
- [x] @zone117x for review

2021-07-06 16:05 UTC, zone117x commented on src/api/init.ts
> +            logger.error(`Error: ${error}`);
This would should probably be a warning rather than error, since we expect this to happen often without there being an actual error in the codebase.

2021-07-06 16:08 UTC, zone117x requested changes
Small comment on the log level used, other than that LGTM!

2021-07-06 16:33 UTC, CharlieC3 commented
@asimm241 After testing this branch in `regtest`, it seems to fix the issue for the affected URL path. You can test against this deployed image here:
https://stacks-node-api.regtest.stacks.co/extended/v1/status

2021-07-06 16:34 UTC, CharlieC3 approved these changes
LGTM once Matt's requested change is resolved! :shipit:

2021-07-07 15:43 UTC, zone117x approved these changes
LGTM thanks @asimm241!

2021-07-07 18:14 UTC, merged

2021-08-11 16:49 UTC, blockstack-devops commented
:tada: This PR is included in version 0.63.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@stacks/stacks-blockchain-api-types/v/0.63.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@stacks/blockchain-api-client/v/0.63.0)
- [GitHub release](https://github.com/blockstack/stacks-blockchain-api/releases/tag/v0.63.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: